# Generated by Django 2.2.6 on 2020-03-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20200316_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[(None, ''), ('M', 'Male'), ('F', 'Female')], max_length=2),
        ),
    ]
