# Generated by Django 2.2.6 on 2020-03-16 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_auto_20200316_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='hire_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 16, 17, 40, 19, 38034)),
        ),
    ]
