# Generated by Django 2.2.6 on 2020-03-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_auto_20200316_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='hire_date',
            field=models.DateField(blank=True, default='2020-03-16'),
        ),
    ]
