# Generated by Django 2.2.6 on 2020-03-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_auto_20200316_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
        migrations.AlterField(
            model_name='staff',
            name='hire_date',
            field=models.DateField(blank=True, default='2020-03-19'),
        ),
    ]
