# Generated by Django 2.2.6 on 2020-03-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_auto_20200319_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='hire_date',
            field=models.DateField(blank=True, default='2020-03-20'),
        ),
    ]
