# Generated by Django 2.2.6 on 2020-03-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0011_auto_20200321_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='hire_date',
            field=models.DateField(blank=True, default='2020-03-23'),
        ),
    ]
