# Generated by Django 2.2.6 on 2020-03-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0016_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['weekday', 'start_time']},
        ),
        migrations.AlterField(
            model_name='staff',
            name='hire_date',
            field=models.DateField(blank=True, default='2020-03-26'),
        ),
    ]
