# Generated by Django 2.2.6 on 2019-12-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='address_other',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='address_work',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='phone_mobile_2',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='schoolenrollment',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
