# Generated by Django 2.2.6 on 2019-12-13 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20191213_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='guardian_1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian_2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='relation_1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='relation_2',
        ),
        migrations.AddField(
            model_name='guardian',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(default='Parent', max_length=50)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_guardian', to='registration.Guardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_guardian', to='registration.Student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='guardians',
            field=models.ManyToManyField(related_name='students', through='registration.StudentGuardian', to='registration.Guardian'),
        ),
    ]
