# Generated by Django 2.2.6 on 2019-12-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20191213_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (0, 'Female')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (0, 'Female')]),
        ),
    ]
