# Generated by Django 2.2.6 on 2019-12-19 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20191217_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guardian',
            options={'ordering': ['last_name_1', 'last_name_2', 'first_name', 'middle_name']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name_1', 'last_name_2', 'first_name', 'middle_name']},
        ),
    ]
