# Generated by Django 2.2.6 on 2019-12-26 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20191220_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Student'),
        ),
        migrations.AlterField(
            model_name='studentguardian',
            name='guardian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_guardian', to='registration.Guardian'),
        ),
        migrations.AlterField(
            model_name='studentguardian',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_guardian', to='registration.Student'),
        ),
    ]
