# Generated by Django 2.2.6 on 2020-03-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20200302_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='last_name_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name_2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
