# Generated by Django 2.2.6 on 2020-03-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20200303_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='address_home',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='phone_mobile_1',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
