# Generated by Django 2.2.6 on 2020-03-11 22:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20200303_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If checked, any other registration for this student will become inactive.', verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='studentguardian',
            name='guardian',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_guardian', to='registration.Guardian'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentguardian',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_guardian', to='registration.Student'),
            preserve_default=False,
        ),
    ]
