# Generated by Django 2.2.6 on 2020-03-13 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20200311_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.Student'),
            preserve_default=False,
        ),
    ]
